-- CREATE A TABLE TO MATCH THE MEMBERS TABLE ON THE SLIDE

CREATE TABLE IF NOT EXISTS members
(
  id INT AUTO_INCREMENT NOT NULL,
  name VARCHAR(225),
  employedId INT,
  PRIMARY KEY(id),
  FOREIGN KEY (employedId) REFERENCES employers(id)
)