CREATE TABLE
IF NOT EXISTS members 
(
    id INT AUTO_INCREMENT UNIQUE NOT NULL,
    name VARCHAR(256) NOT NULL UNIQUE
    memberID INT,
    PRIMARY KEY(id),
    FOREIGN KEY (member_id) REFERENCES employers (id)
)